Amit/home
rifat0153/elvan-flutter pull request #2
Opened 2022-11-28 15:29 UTC by Amit-Aditaya

Bottom Nav UI complete (testing another PR)

2022-11-29 17:06 UTC, Amit-Aditaya commented
custom app bar created, home page background image set

2022-11-30 10:12 UTC, Amit-Aditaya commented
testing pushing branch from forked repo to original repo

2022-11-30 10:54 UTC, rifat0153 commented on lib/features/tabs/screens/tab_screen.dart
> +    LoginScreen(),
Profile screen will be here. When user is not logged in they will be redirected to Login. Will explain to you later.

2022-11-30 10:57 UTC, rifat0153 requested changes
Review the comments and make changes accordingly. For now, make a dummy profile view. Then make a new commit. PR will still remain the same. I will merge it afterward.

2023-03-26 08:42 UTC, closed without merging