Home page UI completed (2)
rifat0153/elvan-flutter pull request #3
Opened 2022-12-03 15:53 UTC by Amit-Aditaya

pushing my work to the new new changes that you made

2022-12-04 09:56 UTC, rifat0153 requested changes
Look at the requested changes and solve them. If you have any questions dm me on FB.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/screens/components/category_items.dart
> +    return Container(
This Container should be a Generic component that behaves like a CARD with rounded corners and shape.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/sections/category_section.dart
> +        const SizedBox(height: 20),
Use constant variables to add size info. e.g. SizedBox(height: kPadding * 2.5) or single constant value to reuse everywhere.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/screens/components/recently_ordered_items.dart
> +          Positioned(
Avoid using hard-coded values for positioning and sizing.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/screens/components/recently_ordered_items.dart
> +      child: Container(
Should be another type of Generic Card.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/screens/components/top_picks_item.dart
> +    return Center(
Make a Generic Component in the shared/components/card folder. There should be three different cards. One for categories, one for top picks, and one for recent orders.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/screens/components/top_picks_section_header.dart
> +        Text(
Use A Shared Text Widget like AppText where you get to pass style or have predefined styles.

2022-12-04 09:56 UTC, rifat0153 commented on lib/features/tabs/ui/screens/components/top_picks_section_header.dart
> +              fontSize: 28,
Use Material 3 sizing from Theme object like -> Theme.of(context).textTheme.bodyLarge. Look at Figma file to know which component uses what material text.

2022-12-04 09:56 UTC, rifat0153 commented on lib/shared/components/appbars/main_appbar.dart
> +import 'package:elvan/shared/components/constants/app_colors.dart';
A more appropriate name is preferred than main_appbar.

2022-12-07 17:22 UTC, Amit-Aditaya commented
changes done except texts, need to discuss about it

2023-01-04 20:07 UTC, closed without merging